name: GL test (Ubuntu 24.04)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Show crun version
        shell: bash
        run: |
          crun --version

      - name: install required packages
        shell: bash
        run: |
          sudo rm -rf /{usr/{local/{lib/{android,heroku},.ghcup,share/{dotnet,powershell,miniconda,swift}},share/{dotnet,miniconda,swift}},opt/{hostedtoolcache,microsoft},imagegeneration}
          sudo docker system prune -a -f
          sudo apt-get update
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends qemu-user-static

      - run: |
          git clone https://github.com/gardenlinux/gardenlinux
          cd gardenlinux
          git checkout 98e59d570b200a16ae01228ef51acf57060a8fa1 # one commit before introducting crun patch
          ./build base-amd64 base-arm64
