name: GL test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show crun version
        shell: bash
        run: |
          crun --version

      - name: install required packages
        shell: bash
        run: |
          sudo rm -rf /{usr/{local/{lib/{android,heroku},.ghcup,share/{dotnet,powershell,miniconda,swift}},share/{dotnet,miniconda,swift}},opt/{hostedtoolcache,microsoft},imagegeneration}
          sudo docker system prune -a -f
          sudo apt-get update
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends qemu-user-static

      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --depth=1 --branch=1312.2 https://github.com/gardenlinux/gardenlinux
          cd gardenlinux
          git commit -am "Version 1312.2"
          ./build base-amd64 base-arm64
