name: Print crun version (Ubuntu 24.04)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Show crun version
        shell: bash
        run: |
          crun --version
